### ISSUE TITLE
version 1.18 error on 1.18

### ISSUE THREAD

**Issue by wackoamd1** [Fourmisain/IndyPets#1]
even though this is classed as a 1.18 mod it doesnt work because of 1 typo in the jar.
in fabric mod.json it says depends on minecraft 1.16.x , 1.17.x which should be 1.16.x, 1.18.x .

just wanted to let u know ,

**Comment by Fourmisain** [comment]
Ah, you got caught in the aftermath, sorry about that!

I was using a fixed version locally since day 1 and thought it actually was 0.7.0, which is why I marked it for 1.18 - just realized the error yesterday 😅

The fixed version 0.7.1 is up and is set to depend on Minecraft `>=1.16`, since it'll most likely work in 1.19 and up too.
