### ISSUE TITLE
[1.1.0] Pets roam while sitting

### ISSUE THREAD

**Issue by V-lpen** [Fourmisain/IndyPets#12]
I know this was implemented as a feature, but if a pet (like a cat or dog) is set to sitting it roams automatically when the player has logged off-
..while still sitting. This is very very cursed involving lots of butt-scooching animals.

**Comment by Fourmisain** [comment]
Hold on, I didn't intend pets to be _this_ real... 😂

Ah, I think I know why this is happening. I can't easily test it, but it should work.

New versions are up!

**Comment by V-lpen** [comment]
Ahh the changelog is hilarious thanks for fixing it!! What version would be for 1.19.2? I see theres 1.18 and 1.19.3+ but not .2

**Comment by Fourmisain** [comment]
Oh, I intentionally did not release a 1.19.2 version since I thought nobody was using it anymore (or there was no reason to use it anymore).

I just backported the change and put a release [here on Github](https://github.com/Fourmisain/IndyPets/releases/tag/1.1.2-1.19.2).
Not sure if I should upload it to CurseForge/Modrinth too tbh.
