### ISSUE TITLE
Idea: compatibility with some tameable "Friends & Foes" mobs

### ISSUE THREAD

**Issue by PieScalzo** [Fourmisain/IndyPets#13]
What the title says!
Particles still show on the Glare from Friends & Foes I tamed, though. Ideally, it shouldn't work with, for example, the copper golem because it's related to the iron golem which wanders where they please (almost) by default

Cheers!

**Comment by Fourmisain** [comment]
Friends&Foes? So let's see...
There's Copper Golems and Moobloms, which aren't tameable, so IndyPets doesn't effect them in any case.
And then there's the Glare...
It is tameable and does follow the player, though they implemented it by copying the AI goal, which means IndyPets needs to explicitly target it, which is always a bit of a hack job (due to build related stuff).

...

I just did it first try. That never happens.
Welp, I guess you can expect a new version soon... :sweat_smile:

**Comment by Fourmisain** [comment]
New versions for 1.19 are up!
I hope you're not playing on 1.18; I tried a simple backport but it failed.
Let me know if you do!

**Comment by PieScalzo** [comment]
"First try" said by a programmer sounds like they channeled magic congrats! haha

I'm playin in 1.19.3. I hope my idea didn't sound like "DEW IT NOW PLZ" haha but hey good job! And thank you!
