### ISSUE TITLE
whistle not working in 1.20

### ISSUE THREAD

**Issue by Thefatsparrow** [Fourmisain/IndyPets#14]
as it states the whistle does not work in 1.20. you can crouch and interact that works but whistle does not sadly

**Comment by Thefatsparrow** [comment]
my bad i had chat turned off in the settings menu turning it back on seems to fix it lol

**Comment by Fourmisain** [comment]
Wait, you are right! I had no idea chat could even be turned off! :smile:

Just checked the Minecraft code and as it turns out, the "chat visibility" setting is actually sent to the server and it's the server that decides to block the whistle command the client has sent!
The more you know 🌠

You can actually set the chat visibility to "command only", which will let commands like whistle through but still block all chat messages.
If you do, I recommend enabling particle effects in the IndyPets config if you haven't already!

**Comment by Thefatsparrow** [comment]
ive also learned if you spam the whistle and unwhistle button too much you get kicked from your own survival world for "spamming" the more you know!
