### ISSUE TITLE
compatibility with sound physics remastered

### ISSUE THREAD

**Issue by Thefatsparrow** [Fourmisain/IndyPets#16]
it would amazing to have compatibility with sound physics so the whistle echos in caves and so other players can hear echos of whistles like when im playing with friends 

https://modrinth.com/mod/sound-physics-remastered

**Comment by Fourmisain** [comment]
> it would amazing to have compatibility with sound physics so the whistle echos in caves

Oh, does that not work? That might be because the sound doesn't actually have a location.
Located sounds have that annoying issue where it doesn't properly sync up with the player's exact position, so you can e.g. hear you own sounds behind you when walking.

I'm not sure if there's a good fix for that.
Maybe only use positioned sound when Sound Physics Remastered is installed? Gonna need to do some testing with that.

> so other players can hear echos of whistles like when im playing with friends

Ah, that part's hard to answer.

I intentionally made the whistle sounds client-only for two main reasons:
 - To keep IndyPets a vanilla-client compatible server mod
 - Whistling was never intended for player communication, just as a fun feedback that you called your pets

I get the idea though, it _would be fun_ to hear the whistling.
Though then one would most likely want a whistle option that _doesn't_ call your pets, which honestly would make more sense as a separate mod.

Still not entirely sure what to do here.

**Comment by Thefatsparrow** [comment]
oh well i dont care much for the other players being able to hear you i just want echos it doesnt bother me really if the sound is not synced up it just breaks the immersion when every sound echos apart from whistling! i hope you can find a way to fix it

**Comment by Thefatsparrow** [comment]
if you could make the sound positioned and just have a setting to turn it on and off that would be good

**Comment by Fourmisain** [comment]
It was indeed that the sounds weren't positioned.
I added a config option for positioned whistle sounds.
New versions are up!

**Comment by Thefatsparrow** [comment]
it sounds so amazing!!! thank you!!
