### ISSUE TITLE
Pet Zones

### ISSUE THREAD

**Issue by BeeFox-sys** [Fourmisain/IndyPets#18]
Pets will only wander in a radius, to prevent them permanently wandering away and getting lost. Server Config Option

**Comment by Fourmisain** [comment]
They already do that.
Do you just need a config option? For the radius?

**Comment by BeeFox-sys** [comment]
oh! i didn't realize! yeah a config for the radius would be nice or more information on that (unless i just can't read)

**Comment by Fourmisain** [comment]
I put a description in the [patch notes](https://modrinth.com/mod/indypets/version/1.2.0+1.19.3) and forgot to add it to the main page. Will do that once this change is out.

Right now, the radius is between 80-128 blocks (5-8 chunks), with a higher chance to head home the further away the pet is:
https://github.com/Fourmisain/IndyPets/blob/26cb2fe2a38f4cf1dbb54583cae06b90b21550fe/src/main/java/com/lizin5ths/indypets/util/IndyPetsUtil.java#L141-L151

I'm not quite sure how exactly the config should look like because it's actually 2 radii.
Maybe just `innerHomeRadius` and `outerHomeRadius`?
Issue is that outer always needs to be larger than inner so I'd have to do some config UI shennanigans.
Maybe have `homeRadius` and a "border", so it goes from `homeRadius` to `homeRadius+border`?
Though that might not be as intuitive...?

Gonna think about that a bit, probably won't get anything done today.

Ah and just so you know, IndyPets doesn't really have server settings.
If a client has the mod installed, it'll always use the client settings (the client sends its config to the server).
While the server does have its own config, it only sets the default values for "vanilla" players (players without IndyPets).

**Comment by Fourmisain** [comment]
Aight, added a setting for the outer radius + a percentage for the inner radius, which you basically never have to change.
Also updated the mod description to mention the "homes"!
