### ISSUE TITLE
Please make pets follow by default

### ISSUE THREAD

**Issue by rein-hub** [Fourmisain/IndyPets#19]
So many players on my server got confused why their newly tamed pets just don't follow them (almost always after they already have gone very far away and dont know where the pet is left at). The default functionality should be like vanilla - pet should follow you. If the player wants then they can set them independent.

It could also be an option in the config, but idk who would want pets to not follow by default.

**Comment by Fourmisain** [comment]
> Ah okay, I checked config but those settings felt like it would just turn the feature completely off, not just if its on by default or not. Would be useful to have some comments next to the options as not all the setting names are self-explanatory.

They do have proper descriptions in the ingame config menu. The names are remnants of old versions and I kept them for backwards compatibility.

> So to double check, setting these to "false" will make the pets follow you by default when tamed like in vanilla, but you can still shift click to make them independent?

Yes!

Be aware though that every player can have their own config.
If a player has the mod installed, it'll use the player's config instead of the server config, so you can't fully "fix" this issue server-side.

**Comment by Fourmisain** [comment]
Just released 1.4.0 which does all that and much more, definitely read the changelog!
