### ISSUE TITLE
[Request] Mob Blacklist

### ISSUE THREAD

**Issue by Estrelaura** [Fourmisain/IndyPets#2]
Some modded mobs don't have a following AI, but they have the sneak+right click nonetheless. It creates some problems interacting with some mobs that use a sneaking interaction. A blacklist would be a fine solution.

**Comment by Fourmisain** [comment]
Got a concrete example? Would make testing easier.

**Comment by Estrelaura** [comment]
The Capybara from the Capybara mod requires sneaking+interacting with a stick to toggle state, and the small snail from Lovely Snails can't be patted if another action already took the place of interacting without sneaking (Gargantuan mod). This actually made interacting with all pets harder since both interactions are taken and you'd need an item in hand to toggle its state. The option of changing the follow AI with some specific item in hand is also welcome.

**Comment by Fourmisain** [comment]
Added the capybara and snail to the default block list, so those will work as intended out of the box.

I was checking the Gargantuan mod too and I think what you mean is this:

> **Grab and Hold**
Right click on a smaller entity while empty-handed to grab and hold them in your right hand.
Right click again on a reachable to place them there.
_Sneak to interact as intended._

I can't do anything about small snails not being pettable by right clicking (that's between Lovely Snails and Gargantuan), but I see the issue with sneak-interacting.

> This actually made interacting with all pets harder since both interactions are taken and you'd need an item in hand to toggle its state.

Yeah, add Pettable (which also uses sneak-interact) into the mix and you get pure chaos, that's the kinda unavoidable issue with entity interactions since there's only one interact button and only one modifier (sneaking) since the server doesn't know about ctrl and alt.
I'm definitely going to add the option to change the follow state with a specific item too.

**Comment by Fourmisain** [comment]
> Added the capybara and snail to the default block list, so those will work as intended out of the box.

Actually, scratch the capybara. Shift-interacting with a stick changes between sitting/standing, which is different from switching the follow behavior. This is one of the cases where a different item for interaction is needed.

**Comment by Fourmisain** [comment]
Released version 0.8.0 with both features! Lemme hear if there's still any issues.
