### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EchoingVoid97** [Fourmisain/IndyPets#4]
Hi! My friend and I are opening a server for their discord  group, and we can't seem to get anything to happen when ever we shift click. we've even messed around in the configs and nothing seems to be happening. Any mods it doesn't work well with?

**Comment by Fourmisain** [comment]
Hm... the only direct conflict I know of is with [Pettable](https://www.curseforge.com/minecraft/mc-mods/pettable) since it uses shift-right click as well, though you probably don't have that installed since you said *nothing* is happening (in case it is actually installed, you can use IndyPets while holding any item).

So let's first get the most basic questions out of the way:
 - Are you using Fabric? The mod won't work on Forge.
 - Is the mod actually installed on the server? (The `latest.log` log file should tell you the list of installed mods.) 
 - Are you shift-right clicking your own, tamed pet?
 - Is the pet modded?

You should see a chat message when shift-right clicking your pet (or a particle effect if `silentMode` is `true`).
If the mod is installed at all, you should notice that your pets won't follow you at all - is that the case?

**Comment by EchoingVoid97** [comment]
Got it working! turns out, i hadn't installed it on the server. lmao

**Comment by Fourmisain** [comment]
That'd certainly explain why it didn't work! :laughing:
