### ISSUE TITLE
Suggestion ( MC 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [Fourmisain/IndyPets#7]
To change modid from examplemod to indypets, because mod Food Ores uses modid examplemod.

**Comment by Kasia1403** [comment]
[latest.log](https://github.com/Fourmisain/IndyPets/files/8984149/latest.log)

**Comment by Fourmisain** [comment]
Hm... sorry but the Forge 1.12 version of this mod is ancient and unsupported, e.g. it only works on the 3 vanilla pets and you can't switch the follow behavior (so you need leads) - there's a reason why the mod page says Fabric all over it.

If you _really_ still wanna use it, I tried changing the metadata with a hex editor here, no guarantee it'll work:

[indypets-1.1 fix.zip](https://github.com/Fourmisain/IndyPets/files/8984744/indypets-1.1.fix.zip) unzip to get the jar file

**Comment by Kasia1403** [comment]
It turns out that when I run Minecraft with this modified file I can't make dog stand up. He is still sitting. Is it fixable ?

**Comment by Kasia1403** [comment]
Maybe it's a conflict with Doggy Talents ? Could You check this ?

**Comment by Fourmisain** [comment]
I quickly checked with [DoggyTalents-1.12.2-1.15.1.6.jar](https://www.curseforge.com/minecraft/mc-mods/doggy-talents/files/3075311) and the dog would sit up.

While trying out the mod I saw that when you give your dog a Doggy Talents' Treat it actually replaces the original dog with a different entity, so maybe that's why your dog behaves weirdly.
If you install [Hwyla](https://www.curseforge.com/minecraft/mc-mods/hwyla/files/2568751) you can see if your dog is a Minecraft Wolf or a Doggy Talents Dog.

The old IndyPets version you're using only works with the vanilla Minecraft pets, so if your dog was converted into a Doggy Talents Dog, IndyPets won't work with it (IndyPets will just do nothing) and it's probably better if you uninstall IndyPets in that case.

If your dog still won't stand up and it is a Doggy Talents Dog, it might be a bug with the Doggy Talents mod.
It could also be another mod that is blocking your right clicks or maybe the game thinks the dog doesn't actually belong to you.
Doggy Talents has an item called "Change Dog Owner", which you can get in creative mode. Maybe giving this to your dog will fix the issue? Give it a try.

The best way to find the cause for issues like this is to temporarily remove mods you suspect could be causing the issue, restart the game and see if the issue is fixed. If it's fixed, then you know it must have been something with the mod you just removed.

Just be careful. If your world contains items, entities or blocks from a mod, removing that mod will also remove those items/entities/blocks. E.g. if your dog is a Doggy Talents Dog, you cannot uninstall the mod without losing your dog in the process.
