### ISSUE TITLE
Pets stop wandering when you move a few blocks away from them

### ISSUE THREAD

**Issue by ImpSpy2** [Fourmisain/IndyPets#9]
Once you move a little bit away they will stop where they are and follow the movement of the player with their head. This is more of a feature request to be closer to the behaviour from the Domestication Innovation mod where the pet is fully independent if you walk away from them than a bug in the mod.

**Comment by Fourmisain** [comment]
Wow, now that you point that out - they absolutely **are** staring!
I never actually noticed because I was mostly using/testing this mod indoors or in small spaces and this doesn't happen at close range. Them stopping after moving out of a certain range looked normal to me - I always thought "they are searching a new goal" or "they are out of simulation distance" or something, but no, that's not it.

What's happening is that the mod keeps the `FollowOwnerGoal` in a constant "starting" state - so the goal is active but doesn't actually cause the follow/teleport behavior. This _does_ however cause the staring behavior and it can even block other goals, which is definitely not the intended behavior!
Looks like this was broken since at least version 0.4.1, oof.

I've now rewritten this to completely abort the goal and it's already looking much better! No staring, proper wandering even in a long distance.
I'll do some more testing on this and finally release it as the 1.0 version, it's only fitting.

Thanks for pointing out this crucial issue!

**Comment by ImpSpy2** [comment]
That's cool to know the details, Thanks for the update!
